/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package teacher_portal_GUI;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import methods.*;
import users.Admin;
import users.Student;
import users.Teacher;

/**
 *
 * @author Edom
 */
public class loggedIn extends javax.swing.JFrame {

    /**
     * Creates new form temp
     */
    public loggedIn() {
        initComponents();
        viewStat.setVisible(false);
        attendance.setVisible(false);
        updateMark.setVisible(false);
        SendAtt.setVisible(false);
        profile.setVisible(false);
        Announcement.setVisible(false);
        home.setVisible(true);
        welcomeName.setText(Transporter.getName());
        
    }
    class JPanelGradient extends JPanel{
    protected void paintComponent(Graphics g){
        Graphics2D g2d=(Graphics2D) g;
        int width=getWidth();
        int height=getHeight();
        
        Color color1=new Color(27,27,27);
        Color color2=new Color(27,27,27);
        GradientPaint gp=new GradientPaint(0,0,color1,180,height,color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, width, height);
    }
}
    class JPanelGradient2 extends JPanel{
    protected void paintComponent(Graphics g){
        Graphics2D g2d=(Graphics2D) g;
        int width=getWidth();
        int height=getHeight();
        
        Color color1=new Color(27,27,27);
        Color color2=new Color(27,27,27);
        GradientPaint gp=new GradientPaint(0,0,color1,180,height,color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, width, height);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        panelSide1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        logOut = new javax.swing.JButton();
        centerPnl = new JPanelGradient();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        home = new JPanelGradient();
        sendAttachments = new javax.swing.JButton();
        updateAttB = new javax.swing.JButton();
        updateMarkB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        welcomeName = new javax.swing.JLabel();
        viewStudents1 = new javax.swing.JButton();
        announce = new javax.swing.JButton();
        attendance = new javax.swing.JPanel();
        panelTop1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        finish = new javax.swing.JButton();
        daySpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelCCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendaceTable = new javax.swing.JTable();
        panelCBottom = new javax.swing.JPanel();
        updateMark = new javax.swing.JPanel();
        markBack = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        finalB1 = new javax.swing.JButton();
        QuizeB1 = new javax.swing.JButton();
        assignB1 = new javax.swing.JButton();
        midB1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        markTable = new javax.swing.JTable();
        profile = new javax.swing.JPanel();
        profileBack = new javax.swing.JPanel();
        detailWindow1 = new javax.swing.JPanel();
        Tname = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Tpass = new javax.swing.JLabel();
        Temail = new javax.swing.JLabel();
        TstN = new javax.swing.JLabel();
        Upenroll = new javax.swing.JButton();
        Upemail = new javax.swing.JButton();
        Uppass = new javax.swing.JButton();
        editName = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        Tsec = new javax.swing.JLabel();
        UpSec = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        Editorial = new javax.swing.JPanel();
        newPass = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        newName = new javax.swing.JTextField();
        newEmail = new javax.swing.JTextField();
        commit = new javax.swing.JButton();
        newSec = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        SendAtt = new javax.swing.JPanel();
        viewBack1 = new javax.swing.JPanel();
        subject = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jFileChooser = new javax.swing.JFileChooser();
        Announcement = new javax.swing.JPanel();
        Aback = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        viewStat = new javax.swing.JPanel();
        viewBack = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        detailWindow = new javax.swing.JPanel();
        Dname = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Datt = new javax.swing.JLabel();
        Dfin = new javax.swing.JLabel();
        Dmid = new javax.swing.JLabel();
        Das = new javax.swing.JLabel();
        Dquize = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DTB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 25));

        mainPnl.setBackground(new java.awt.Color(24, 27, 25));
        mainPnl.setLayout(new java.awt.BorderLayout());

        panelSide1.setBackground(new java.awt.Color(78, 151, 126));
        panelSide1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        panelSide1.setPreferredSize(new java.awt.Dimension(70, 0));

        jPanel4.setBackground(new java.awt.Color(78, 151, 126));
        jPanel4.setPreferredSize(new java.awt.Dimension(120, 530));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50));

        jPanel5.setBackground(new java.awt.Color(78, 151, 126));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50));
        jPanel4.add(jPanel5);

        homeBtn.setBackground(new java.awt.Color(78, 151, 126));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/home_32px.png"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnpage(evt);
            }
        });
        jPanel4.add(homeBtn);

        profileBtn.setBackground(new java.awt.Color(78, 151, 126));
        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/businessman_26px.png"))); // NOI18N
        profileBtn.setBorder(null);
        profileBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnprofileAction(evt);
            }
        });
        jPanel4.add(profileBtn);

        logOut.setBackground(new java.awt.Color(78, 151, 126));
        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/exit_32px.png"))); // NOI18N
        logOut.setBorder(null);
        logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOut.setPreferredSize(new java.awt.Dimension(40, 40));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel4.add(logOut);

        panelSide1.add(jPanel4);

        mainPnl.add(panelSide1, java.awt.BorderLayout.WEST);

        centerPnl.setBackground(new java.awt.Color(27, 27, 27));
        centerPnl.setPreferredSize(new java.awt.Dimension(1030, 616));
        centerPnl.setRequestFocusEnabled(false);
        centerPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(24, 27, 25));
        jLayeredPane1.setForeground(new java.awt.Color(4, 36, 14));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1030, 610));

        home.setBackground(new java.awt.Color(27, 27, 27));
        home.setForeground(new java.awt.Color(27, 27, 27));
        home.setMinimumSize(new java.awt.Dimension(728, 528));
        home.setOpaque(false);
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendAttachments.setBackground(new java.awt.Color(0, 0, 0));
        sendAttachments.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        sendAttachments.setForeground(new java.awt.Color(153, 153, 153));
        sendAttachments.setText("Send Attchments");
        sendAttachments.setBorder(null);
        sendAttachments.setPreferredSize(new java.awt.Dimension(200, 50));
        sendAttachments.setRolloverEnabled(false);
        sendAttachments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAttachmentsActionPerformed(evt);
            }
        });
        home.add(sendAttachments, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 240, -1));

        updateAttB.setBackground(new java.awt.Color(0, 0, 0));
        updateAttB.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        updateAttB.setForeground(new java.awt.Color(153, 153, 153));
        updateAttB.setText("Update Attendance");
        updateAttB.setBorder(null);
        updateAttB.setPreferredSize(new java.awt.Dimension(200, 50));
        updateAttB.setRolloverEnabled(false);
        updateAttB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAttendance(evt);
            }
        });
        home.add(updateAttB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 240, -1));

        updateMarkB.setBackground(new java.awt.Color(0, 0, 0));
        updateMarkB.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        updateMarkB.setForeground(new java.awt.Color(153, 153, 153));
        updateMarkB.setText("Update Mark Sheet");
        updateMarkB.setBorder(null);
        updateMarkB.setPreferredSize(new java.awt.Dimension(200, 50));
        updateMarkB.setRolloverEnabled(false);
        updateMarkB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMarkBActionPerformed(evt);
            }
        });
        home.add(updateMarkB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 240, -1));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Welcome Inst.");
        jLabel2.setToolTipText("");
        home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, -1));

        welcomeName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        welcomeName.setForeground(new java.awt.Color(153, 153, 153));
        home.add(welcomeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 235, 50));

        viewStudents1.setBackground(new java.awt.Color(0, 0, 0));
        viewStudents1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        viewStudents1.setForeground(new java.awt.Color(153, 153, 153));
        viewStudents1.setText("View Student Status");
        viewStudents1.setBorder(null);
        viewStudents1.setPreferredSize(new java.awt.Dimension(200, 50));
        viewStudents1.setRolloverEnabled(false);
        viewStudents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudents1ActionPerformed(evt);
            }
        });
        home.add(viewStudents1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 240, -1));

        announce.setBackground(new java.awt.Color(0, 0, 0));
        announce.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        announce.setForeground(new java.awt.Color(153, 153, 153));
        announce.setText("Announcement");
        announce.setActionCommand("Announcement");
        announce.setBorder(null);
        announce.setPreferredSize(new java.awt.Dimension(200, 50));
        announce.setRolloverEnabled(false);
        announce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announceActionPerformed(evt);
            }
        });
        home.add(announce, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 240, 50));

        attendance.setBackground(new java.awt.Color(172, 161, 144));
        attendance.setPreferredSize(new java.awt.Dimension(777, 507));
        attendance.setLayout(new java.awt.BorderLayout());

        panelTop1.setBackground(new java.awt.Color(27, 27, 27));
        panelTop1.setForeground(new java.awt.Color(102, 102, 102));
        panelTop1.setPreferredSize(new java.awt.Dimension(0, 100));

        jLabel3.setBackground(new java.awt.Color(63, 78, 79));
        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("ATTENDANCE");

        finish.setBackground(new java.awt.Color(6, 6, 6));
        finish.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        finish.setForeground(new java.awt.Color(102, 102, 102));
        finish.setText("Finish");
        finish.setPreferredSize(new java.awt.Dimension(60, 23));
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        daySpinner.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        daySpinner.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Day:");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("changes made are irreversable!!");

        javax.swing.GroupLayout panelTop1Layout = new javax.swing.GroupLayout(panelTop1);
        panelTop1.setLayout(panelTop1Layout);
        panelTop1Layout.setHorizontalGroup(
            panelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTop1Layout.createSequentialGroup()
                .addGroup(panelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTop1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTop1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGap(19, 19, 19))
        );
        panelTop1Layout.setVerticalGroup(
            panelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTop1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        attendance.add(panelTop1, java.awt.BorderLayout.NORTH);

        panelCCenter.setBackground(new java.awt.Color(27, 27, 27));
        panelCCenter.setPreferredSize(new java.awt.Dimension(766, 507));

        attendaceTable.setBackground(new java.awt.Color(75, 82, 77));
        attendaceTable.setForeground(new java.awt.Color(255, 255, 255));
        attendaceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Name", "ID", "Present"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        attendaceTable.setPreferredSize(new java.awt.Dimension(380, 300));
        jScrollPane1.setViewportView(attendaceTable);

        javax.swing.GroupLayout panelCCenterLayout = new javax.swing.GroupLayout(panelCCenter);
        panelCCenter.setLayout(panelCCenterLayout);
        panelCCenterLayout.setHorizontalGroup(
            panelCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCCenterLayout.setVerticalGroup(
            panelCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCCenterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        attendance.add(panelCCenter, java.awt.BorderLayout.CENTER);

        panelCBottom.setBackground(new java.awt.Color(27, 27, 27));
        panelCBottom.setPreferredSize(new java.awt.Dimension(0, 80));

        javax.swing.GroupLayout panelCBottomLayout = new javax.swing.GroupLayout(panelCBottom);
        panelCBottom.setLayout(panelCBottomLayout);
        panelCBottomLayout.setHorizontalGroup(
            panelCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        panelCBottomLayout.setVerticalGroup(
            panelCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        attendance.add(panelCBottom, java.awt.BorderLayout.SOUTH);

        updateMark.setBackground(new java.awt.Color(24, 27, 25));
        updateMark.setPreferredSize(new java.awt.Dimension(777, 507));
        updateMark.setLayout(new java.awt.BorderLayout());

        markBack.setBackground(new java.awt.Color(27, 27, 27));
        markBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Update:");
        markBack.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 131, 49));

        finalB1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        finalB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/exam_32px.png"))); // NOI18N
        finalB1.setText("Final");
        finalB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalB1ActionPerformed(evt);
            }
        });
        markBack.add(finalB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 229, 189, 63));

        QuizeB1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        QuizeB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/quiz_32px.png"))); // NOI18N
        QuizeB1.setText("Quiz");
        QuizeB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizeB1ActionPerformed(evt);
            }
        });
        markBack.add(QuizeB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 82, 189, 63));

        assignB1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        assignB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/group_of_projects_32px.png"))); // NOI18N
        assignB1.setText("Assignment");
        assignB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignB1ActionPerformed(evt);
            }
        });
        markBack.add(assignB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 376, 189, 63));

        midB1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        midB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/terms_and_conditions_32px.png"))); // NOI18N
        midB1.setText("Mid Exam");
        midB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midB1ActionPerformed(evt);
            }
        });
        markBack.add(midB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 523, 189, 63));

        markTable.setBackground(new java.awt.Color(75, 82, 77));
        markTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(markTable);

        markBack.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 82, 356, 510));

        updateMark.add(markBack, java.awt.BorderLayout.CENTER);

        profile.setBackground(new java.awt.Color(24, 27, 25));
        profile.setPreferredSize(new java.awt.Dimension(777, 507));
        profile.setLayout(new java.awt.BorderLayout());

        profileBack.setBackground(new java.awt.Color(27, 27, 27));
        profileBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailWindow1.setBackground(new java.awt.Color(27, 40, 31));
        detailWindow1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tname.setBackground(new java.awt.Color(255, 255, 255));
        Tname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tname.setForeground(new java.awt.Color(153, 153, 153));
        detailWindow1.add(Tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 130, 32));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name:");
        detailWindow1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 83, 32));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Number of Students:");
        detailWindow1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 32));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email:");
        detailWindow1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 32));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Password:");
        detailWindow1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 32));

        Tpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tpass.setForeground(new java.awt.Color(153, 153, 153));
        detailWindow1.add(Tpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, 32));

        Temail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Temail.setForeground(new java.awt.Color(153, 153, 153));
        detailWindow1.add(Temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, 32));

        TstN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TstN.setForeground(new java.awt.Color(153, 153, 153));
        detailWindow1.add(TstN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, 32));

        Upenroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/edit_32px.png"))); // NOI18N
        Upenroll.setContentAreaFilled(false);
        Upenroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Upenroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpenrollActionPerformed(evt);
            }
        });
        detailWindow1.add(Upenroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, 30));

        Upemail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/edit_32px.png"))); // NOI18N
        Upemail.setContentAreaFilled(false);
        Upemail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Upemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpemailActionPerformed(evt);
            }
        });
        detailWindow1.add(Upemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 40, 30));

        Uppass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/edit_32px.png"))); // NOI18N
        Uppass.setContentAreaFilled(false);
        Uppass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Uppass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UppassActionPerformed(evt);
            }
        });
        detailWindow1.add(Uppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 40, 30));

        editName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/edit_32px.png"))); // NOI18N
        editName.setContentAreaFilled(false);
        editName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNameActionPerformed(evt);
            }
        });
        detailWindow1.add(editName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 40, 30));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Section Name:");
        detailWindow1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 32));

        Tsec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tsec.setForeground(new java.awt.Color(153, 153, 153));
        detailWindow1.add(Tsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, 32));

        UpSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/edit_32px.png"))); // NOI18N
        UpSec.setContentAreaFilled(false);
        UpSec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpSecActionPerformed(evt);
            }
        });
        detailWindow1.add(UpSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 40, 30));

        profileBack.add(detailWindow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 380, 350));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Editorial:");
        profileBack.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 131, 49));

        Editorial.setBackground(new java.awt.Color(83, 93, 81));
        Editorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newPass.setBackground(new java.awt.Color(24, 27, 25));
        newPass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newPass.setForeground(new java.awt.Color(102, 102, 102));
        Editorial.add(newPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 204, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Password:");
        Editorial.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 99, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("New name:");
        Editorial.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 99, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("New Email:");
        Editorial.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 99, 40));

        newName.setBackground(new java.awt.Color(24, 27, 25));
        newName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newName.setForeground(new java.awt.Color(102, 102, 102));
        Editorial.add(newName, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 21, 204, 40));

        newEmail.setBackground(new java.awt.Color(24, 27, 25));
        newEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newEmail.setForeground(new java.awt.Color(102, 102, 102));
        Editorial.add(newEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 204, 40));

        commit.setBackground(new java.awt.Color(24, 27, 25));
        commit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        commit.setText("Commit");
        commit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitActionPerformed(evt);
            }
        });
        Editorial.add(commit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 100, 30));

        newSec.setBackground(new java.awt.Color(24, 27, 25));
        newSec.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newSec.setForeground(new java.awt.Color(102, 102, 102));
        Editorial.add(newSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 204, 40));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Sec name:");
        Editorial.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 99, 40));

        profileBack.add(Editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 350, 340));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Profile:");
        profileBack.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 131, 49));

        profile.add(profileBack, java.awt.BorderLayout.CENTER);

        SendAtt.setBackground(new java.awt.Color(24, 27, 25));
        SendAtt.setPreferredSize(new java.awt.Dimension(777, 507));
        SendAtt.setLayout(new java.awt.BorderLayout());

        viewBack1.setBackground(new java.awt.Color(27, 27, 27));
        viewBack1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subject.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        viewBack1.add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 240, 51));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        viewBack1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 120, 40));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Enter subject/purpose:");
        viewBack1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 160, 30));

        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });
        viewBack1.add(jFileChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 20, 630, 340));

        SendAtt.add(viewBack1, java.awt.BorderLayout.CENTER);

        Announcement.setBackground(new java.awt.Color(24, 27, 25));
        Announcement.setPreferredSize(new java.awt.Dimension(777, 507));
        Announcement.setLayout(new java.awt.BorderLayout());

        Aback.setBackground(new java.awt.Color(27, 27, 27));
        Aback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Make an announcement");
        Aback.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 400, 50));

        textarea.setBackground(new java.awt.Color(27, 27, 27));
        textarea.setColumns(20);
        textarea.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        textarea.setForeground(new java.awt.Color(255, 255, 255));
        textarea.setRows(5);
        textarea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jScrollPane4.setViewportView(textarea);

        Aback.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 420, 190));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Enter message:");
        Aback.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 90, 100, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton2.setText("Broadcast");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Aback.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 323, 110, 40));

        Announcement.add(Aback, java.awt.BorderLayout.CENTER);

        viewStat.setBackground(new java.awt.Color(24, 27, 25));
        viewStat.setPreferredSize(new java.awt.Dimension(777, 507));
        viewStat.setLayout(new java.awt.BorderLayout());

        viewBack.setBackground(new java.awt.Color(27, 27, 27));
        viewBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Details");
        viewBack.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 131, 49));

        viewTable.setBackground(new java.awt.Color(57, 61, 57));
        viewTable.setForeground(new java.awt.Color(255, 255, 255));
        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(viewTable);

        viewBack.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, 500));

        detailWindow.setBackground(new java.awt.Color(27, 40, 31));
        detailWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dname.setBackground(new java.awt.Color(255, 255, 255));
        Dname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dname.setForeground(new java.awt.Color(255, 255, 255));
        detailWindow.add(Dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 130, 32));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name:");
        detailWindow.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 83, 32));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quiz:");
        detailWindow.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 83, 32));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Assignmnet:");
        detailWindow.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 32));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mid Exam:");
        detailWindow.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 83, 32));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Final:");
        detailWindow.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 83, 32));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Attendance Rate:");
        detailWindow.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 130, 32));

        Datt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Datt.setForeground(new java.awt.Color(255, 255, 255));
        detailWindow.add(Datt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 130, 32));

        Dfin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dfin.setForeground(new java.awt.Color(255, 255, 255));
        detailWindow.add(Dfin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, 32));

        Dmid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dmid.setForeground(new java.awt.Color(255, 255, 255));
        detailWindow.add(Dmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, 32));

        Das.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Das.setForeground(new java.awt.Color(255, 255, 255));
        detailWindow.add(Das, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, 32));

        Dquize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Dquize.setForeground(new java.awt.Color(255, 255, 255));
        detailWindow.add(Dquize, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 130, 32));

        viewBack.add(detailWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 340, 400));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("View");
        viewBack.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 131, 49));

        DTB.setBackground(new java.awt.Color(51, 51, 51));
        DTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/double_right_32px.png"))); // NOI18N
        DTB.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        DTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DTBActionPerformed(evt);
            }
        });
        viewBack.add(DTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 60, 60));

        viewStat.add(viewBack, java.awt.BorderLayout.CENTER);

        jLayeredPane1.setLayer(home, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(attendance, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(updateMark, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(profile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SendAtt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Announcement, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(viewStat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1112, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 39, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(viewStat, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(111, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateMark, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SendAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Announcement, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(viewStat, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(66, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateMark, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SendAtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Announcement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        centerPnl.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1030, 610));

        mainPnl.add(centerPnl, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPnl, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnpage(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnpage
        viewStat.setVisible(false);
        updateMark.setVisible(false);
        attendance.setVisible(false);
        profile.setVisible(false);
        SendAtt.setVisible(false);
        Announcement.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_homeBtnpage

    private void profileBtnprofileAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnprofileAction
        viewStat.setVisible(false);
        updateMark.setVisible(false);
        attendance.setVisible(false);
        home.setVisible(false);
        SendAtt.setVisible(false);
        Announcement.setVisible(false);
        profile.setVisible(true);
        
        Teacher teacher = new Teacher(Transporter.getName(), Transporter.getId(),Transporter.getPassword(),Transporter.getEmail(),Transporter.getSec());
        Tname.setText(Transporter.getName());
        Tpass.setText(Transporter.getSec());
        Temail.setText(Transporter.getEmail());
        Tpass.setText(Transporter.getPassword());
        String num = "" + teacher.countStudents();
        TstN.setText(num);
        Tsec.setText(Transporter.getSec());
        
        newName.setEnabled(false);
        newEmail.setEnabled(false);
        newSec.setEnabled(false);
        newPass.setEnabled(false);
    }//GEN-LAST:event_profileBtnprofileAction

    private void updateMarkBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMarkBActionPerformed
        // TODO add your handling code here 
        attendance.setVisible(false);
        home.setVisible(false);
        viewStat.setVisible(false);
        SendAtt.setVisible(false);
        Announcement.setVisible(false);
        updateMark.setVisible(true); 
        
        DefaultTableModel model = (DefaultTableModel) markTable.getModel();
        model.setRowCount(0);
        
        String fileName;
        fileName = Transporter.getName()+ Transporter.getSec()+"(Attendance).csv";
        
        List<String[]> myData = new ArrayList<>();
        myData = Read.takeTheWholeAttendance(fileName);
        
        String[] display = new String[2];
        
        for(int i = 1; i < myData.size(); ++i)
        {
            display[0] = myData.get(i)[0];
            display[1] = myData.get(i)[1];
            model.addRow(display);
        }
        
    }//GEN-LAST:event_updateMarkBActionPerformed

    private void UpdateAttendance(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAttendance
        // TODO add your handling code here:
        viewStat.setVisible(false);
        home.setVisible(false);
        updateMark.setVisible(false);
        SendAtt.setVisible(false);
        Announcement.setVisible(false);
        attendance.setVisible(true);
       
        DefaultTableModel model = (DefaultTableModel) attendaceTable.getModel();
        model.setRowCount(0);
        
        String fileName;
        fileName = Transporter.getName()+ Transporter.getSec()+"(Attendance).csv";
        
        List<String[]> myData = new ArrayList<>();
        myData = Read.takeTheWholeAttendance(fileName);
        String[] display = new String[3];
        
        for(int i = 1; i < myData.size(); ++i)
        {
            display[0] =  myData.get(i)[1];
            display[1] =  myData.get(i)[0];
            
             
           model.addRow(display);
           
        }
    }//GEN-LAST:event_UpdateAttendance

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:
        Main back = new Main();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_logOutActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        Teacher teacher = new Teacher(Transporter.getName() , Transporter.getId() , Transporter.getPassword() , Transporter.getEmail() , Transporter.getSec());
        TableModel model = attendaceTable.getModel();
        
            if((int)daySpinner.getValue() > 10 || (int)daySpinner.getValue() < 1)
            {
                JOptionPane.showMessageDialog(this,"Invalid Date!!");
            }
            else
            {
                Boolean flag;
                for(int i = 0; i < model.getRowCount(); ++i)
                {
                    
                   if(model.getValueAt(i,model.getColumnCount()-1) == null)
                   {
                      flag = false;
                   }
                   else
                   {
                       flag = true;  
                   }
                    if(flag)
                    {
                      Student stud = new Student((String)model.getValueAt(i, 0) , Integer.parseInt((String) model.getValueAt(i,1)) , "");
                      teacher.updateAttendance(stud, (int)daySpinner.getValue());
                }  
            }
                attendance.setVisible(false);
                home.setVisible(true);
        }

    }//GEN-LAST:event_finishActionPerformed

    private void sendAttachmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAttachmentsActionPerformed
        // TODO add your handling code here:
        attendance.setVisible(false);
        home.setVisible(false);
        viewStat.setVisible(false);
        SendAtt.setVisible(true);
        Announcement.setVisible(false);
        updateMark.setVisible(false);
        
        
        
    }//GEN-LAST:event_sendAttachmentsActionPerformed

    private void finalB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalB1ActionPerformed
        // TODO add your handling code here:
        int row = markTable.getSelectedRow();
        if(row != -1)
        {
            Final F = new Final();

            String name = (String)markTable.getValueAt(row, 1);
            int id = Integer.parseInt((String)markTable.getValueAt(row, 0));
            Student std = new Student(name , id , "");

            TransportStud T = new TransportStud(std);
            F.setVisible(true);
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row!");
        }


    }//GEN-LAST:event_finalB1ActionPerformed

    private void QuizeB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizeB1ActionPerformed
        // TODO add your handling code here:
        
        int row = markTable.getSelectedRow();
        if(row != -1)
        {
            Quiz F = new Quiz();
            String name = (String)markTable.getValueAt(row, 1);
            int id = Integer.parseInt((String)markTable.getValueAt(row, 0));
            Student std = new Student(name , id , "");

            TransportStud T = new TransportStud(std);
            F.setVisible(true);
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row!");
        }

    }//GEN-LAST:event_QuizeB1ActionPerformed

    private void assignB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignB1ActionPerformed
        // TODO add your handling code here:
        int row = markTable.getSelectedRow();
        if(row != -1)
        {
            Assignment F = new Assignment();

            String name = (String)markTable.getValueAt(row, 1);
            int id = Integer.parseInt((String)markTable.getValueAt(row, 0));
            Student std = new Student(name , id , "");

            TransportStud T = new TransportStud(std);
            F.setVisible(true);
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row!");
        }

    }//GEN-LAST:event_assignB1ActionPerformed

    private void midB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midB1ActionPerformed
        // TODO add your handling code here:
        int row = markTable.getSelectedRow();
        if(row != -1)
        {
            Mid F = new Mid();

            String name = (String)markTable.getValueAt(row, 1);
            int id = Integer.parseInt((String)markTable.getValueAt(row, 0));
            Student std = new Student(name , id , "");

            TransportStud T = new TransportStud(std);
            F.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row!");
        }

    }//GEN-LAST:event_midB1ActionPerformed

    private void DTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DTBActionPerformed
        // TODO add your handling code here:
        int row = viewTable.getSelectedRow();
        String name = (String)viewTable.getValueAt(row, 1);
        int id = Integer.parseInt((String)viewTable.getValueAt(row, 0));
        String email = (String)viewTable.getValueAt(row, 2);
        
        Student stud = new Student(name,id,email);
        Teacher teacher = new Teacher(Transporter.getName() , Transporter.getId() , Transporter.getPassword() , Transporter.getEmail() , Transporter.getSec());
        String fileName;
        fileName = Transporter.getName()+ Transporter.getSec()+"(Mark).csv";
        
        List<String[]> myData = new ArrayList<>();
        myData = Read.takeTheWholeMark(fileName);
        
        String [] myEnt = new String[6];
        
        myEnt = Search.markSheet(fileName, id);
        
        Das.setText(myEnt[4]+ " /15");
        Dfin.setText(myEnt[5]+ " /50");
        Dmid.setText(myEnt[3]+ " /30");
        Dname.setText(myEnt[1]+ "");
        Dquize.setText(myEnt[2] + " /5");
        
        String AttRate = teacher.attendancePercentage(stud, 10) + " %";
        Datt.setText(AttRate);
    }//GEN-LAST:event_DTBActionPerformed

    private void editNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNameActionPerformed
        // TODO add your handling code here:
        newName.setEnabled(true);
        newEmail.setEnabled(false);
        newSec.setEnabled(false);
        newPass.setEnabled(false);
    }//GEN-LAST:event_editNameActionPerformed

    private void UpenrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpenrollActionPerformed
        // TODO add your handling code here:
                        
        updateStudents S = new updateStudents();
        S.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_UpenrollActionPerformed

    private void UpemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpemailActionPerformed
        // TODO add your handling code here:
        newName.setEnabled(false);
        newEmail.setEnabled(true);
        newSec.setEnabled(false);
        newPass.setEnabled(false);
    }//GEN-LAST:event_UpemailActionPerformed

    private void UpSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpSecActionPerformed
        // TODO add your handling code here:
        newName.setEnabled(false);
        newEmail.setEnabled(false);
        newSec.setEnabled(true);
        newPass.setEnabled(false);
    }//GEN-LAST:event_UpSecActionPerformed

    private void UppassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UppassActionPerformed
        // TODO add your handling code here:
        newName.setEnabled(false);
        newEmail.setEnabled(false);
        newSec.setEnabled(false);
        newPass.setEnabled(true);
    }//GEN-LAST:event_UppassActionPerformed

    private void commitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitActionPerformed
        // TODO add your handling code here:
        Admin admin = new Admin( "", 1 , "","","");
        Teacher teacher = new Teacher(Transporter.getName() , Transporter.getId() , Transporter.getPassword() , Transporter.getEmail() , Transporter.getSec());
        String name = newName.getText();
        String sec = newSec.getText();
        String email = newEmail.getText();
        String password = newPass.getText();
        
        if(newName.isEnabled() && !name.equals(""))
        {
            if(admin.updateName(teacher, name))
            {
                JOptionPane.showMessageDialog(this,"Name has been Updated");
                Teacher Nteacher = new Teacher(name , Transporter.getId() , Transporter.getPassword() , Transporter.getEmail() , Transporter.getSec());
                Transporter T = new Transporter(Nteacher);
            }   
            else
            {
                JOptionPane.showMessageDialog(this,"This name already exists, please choose another one!!");
            }
            
        }
        
        else if(newSec.isEnabled() && !sec.equals(""))
        {
            if(admin.updateSection(teacher, sec))
            {
                JOptionPane.showMessageDialog(this,"Section name has been Updated");
                Teacher Nteacher = new Teacher(Transporter.getName() , Transporter.getId() , Transporter.getPassword() , Transporter.getEmail() , sec);
                Transporter T = new Transporter(Nteacher);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"This section name already exists, please choose another one!!");
            }
        }
        
        else if(newEmail.isEnabled() && !email.equals(""))
        {
            if(admin.updateEmail(teacher, email))
            {
                JOptionPane.showMessageDialog(this,"email has been Updated");
                Teacher Nteacher = new Teacher(Transporter.getName() , Transporter.getId() , Transporter.getPassword() , email , Transporter.getSec());
                Transporter T = new Transporter(Nteacher);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"This is not a valid email!");
            }
        }
        
        else if(newPass.isEnabled() && !password.equals(""))
        {
           admin.updatePassword(teacher, password);
           JOptionPane.showMessageDialog(this,"Password has been Updated");
           Teacher Nteacher = new Teacher(Transporter.getName() , Transporter.getId() , password , Transporter.getEmail() , Transporter.getSec());
           Transporter T = new Transporter(Nteacher);
        }

    }//GEN-LAST:event_commitActionPerformed

    private void viewStudents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudents1ActionPerformed
        
        viewStat.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) viewTable.getModel();
        model.setRowCount(0);
        
        String fileName;
        fileName = Transporter.getName()+ Transporter.getSec()+"(Attendance).csv";
        
        List<String[]> myData = new ArrayList<>();
        myData = Read.takeTheWholeAttendance(fileName);
        String[] display = new String[3];
        
        for(int i = 1; i < myData.size(); ++i)
        {
            display[0] = myData.get(i)[0];
            display[1] = myData.get(i)[1];
            display[2] = myData.get(i)[12];
            
            model.addRow(display);
        }

    }//GEN-LAST:event_viewStudents1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        File file = jFileChooser.getSelectedFile();
        String sub = subject.getText();
        
        
        
        if(sub.equals(""))
        {
            JOptionPane.showMessageDialog(this,  "Please complete the form!");
        }
        else
        {
            boolean flag = true;
            String fileName;
            fileName = Transporter.getName()+ Transporter.getSec()+"(Attendance).csv";

            List<String[]> myData = new ArrayList<>();
            myData = Read.takeTheWholeAttendance(fileName);
            
            for(int i = 1; i < myData.size();++i)
            {
                String email = myData.get(i)[12];
                
                String mess = "Dear "+ myData.get(i)[1] + " this an attachment is sent from your instructor " + Transporter.getName();
                SendAttachment attach = new SendAttachment(file.getAbsolutePath() , email, Transporter.getName() , sub , mess );
                if(!attach.send())
                {
                
                    JOptionPane.showMessageDialog(this, "There seems to be a problem sending the email please check your connecton or the file path!");
                    flag = false;
                    break;
                }
                
            }
            if(flag)
            {
                JOptionPane.showMessageDialog(this,  "The attachment has been sent!");
                SendAtt.setVisible(false);
                home.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
        // TODO add your handling code here:SSS
        
    }//GEN-LAST:event_jFileChooserActionPerformed

    private void announceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announceActionPerformed
        // TODO add your handling code here:
        
        viewStat.setVisible(false);
        updateMark.setVisible(false);
        attendance.setVisible(false);
        profile.setVisible(false);
        SendAtt.setVisible(false);
        Announcement.setVisible(true);
        home.setVisible(false);
    }//GEN-LAST:event_announceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String text = textarea.getText();
        
        if (!text.equals(""))
        {
            String fileName;
            fileName = Transporter.getName()+ Transporter.getSec()+"(Attendance).csv";

            List<String[]> myData = new ArrayList<>();
            myData = Read.takeTheWholeAttendance(fileName);
            
            for(int i = 1; i < myData.size();++i)
            {
                String email = myData.get(i)[12];
                
                
                SendEmail broad = new SendEmail(email , Transporter.getName() , "Dear " + myData.get(i)[1]+ " " + text);
                
                try {
                    if (broad.send())
                    {
                        JOptionPane.showMessageDialog(this,"Broadcast Successfull!");   
                    } else {
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "There seems to be a problem sending the email please check your connecton!");
                    break;
                }
                
            }
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loggedIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loggedIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aback;
    private javax.swing.JPanel Announcement;
    private javax.swing.JButton DTB;
    private javax.swing.JLabel Das;
    private javax.swing.JLabel Datt;
    private javax.swing.JLabel Dfin;
    private javax.swing.JLabel Dmid;
    private javax.swing.JLabel Dname;
    private javax.swing.JLabel Dquize;
    private javax.swing.JPanel Editorial;
    private javax.swing.JButton QuizeB1;
    private javax.swing.JPanel SendAtt;
    private javax.swing.JLabel Temail;
    private javax.swing.JLabel Tname;
    private javax.swing.JLabel Tpass;
    private javax.swing.JLabel Tsec;
    private javax.swing.JLabel TstN;
    private javax.swing.JButton UpSec;
    private javax.swing.JButton Upemail;
    private javax.swing.JButton Upenroll;
    private javax.swing.JButton Uppass;
    private javax.swing.JButton announce;
    private javax.swing.JButton assignB1;
    private javax.swing.JTable attendaceTable;
    private javax.swing.JPanel attendance;
    private javax.swing.JPanel centerPnl;
    private javax.swing.JButton commit;
    private javax.swing.JSpinner daySpinner;
    private javax.swing.JPanel detailWindow;
    private javax.swing.JPanel detailWindow1;
    private javax.swing.JButton editName;
    private javax.swing.JButton finalB1;
    private javax.swing.JButton finish;
    private javax.swing.JPanel home;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton logOut;
    private javax.swing.JPanel mainPnl;
    private javax.swing.JPanel markBack;
    private javax.swing.JTable markTable;
    private javax.swing.JButton midB1;
    private javax.swing.JTextField newEmail;
    private javax.swing.JTextField newName;
    private javax.swing.JTextField newPass;
    private javax.swing.JTextField newSec;
    private javax.swing.JPanel panelCBottom;
    private javax.swing.JPanel panelCCenter;
    private javax.swing.JPanel panelSide1;
    private javax.swing.JPanel panelTop1;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel profileBack;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton sendAttachments;
    private javax.swing.JTextField subject;
    private javax.swing.JTextArea textarea;
    private javax.swing.JButton updateAttB;
    private javax.swing.JPanel updateMark;
    private javax.swing.JButton updateMarkB;
    private javax.swing.JPanel viewBack;
    private javax.swing.JPanel viewBack1;
    private javax.swing.JPanel viewStat;
    private javax.swing.JButton viewStudents1;
    private javax.swing.JTable viewTable;
    private javax.swing.JLabel welcomeName;
    // End of variables declaration//GEN-END:variables
}
